name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: write

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
      - if: always()
        name: Get sha_short
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - if: always()
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "report.md"
          makeLatest: true
          tag: ${{ env.sha_short }}
